name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash -n scripts/run.sh
      - run: bash -n scripts/test.sh
      - run: ./scripts/test.sh
